### ISSUE TITLE
httpcore.ReadTimeout: The read operation timed out

### ISSUE THREAD

**Issue by redooo98** [MainKronos/AnimeWorld-API#9]
Da ieri sera continuo a riceve il seguente errore:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 28, in read
    return self._sock.recv(max_bytes)
  File "/usr/lib/python3.10/ssl.py", line 1259, in recv
    return self.read(buflen)
  File "/usr/lib/python3.10/ssl.py", line 1132, in read
    return self._sslobj.read(len)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 261, in handle_request
    raise exc
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 96, in handle_request
    return self._connection.handle_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_sync/http2.py", line 157, in handle_request
    raise exc
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_sync/http2.py", line 125, in handle_request
    status, headers = self._receive_response(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_sync/http2.py", line 242, in _receive_response
    event = self._receive_stream_event(request, stream_id)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_sync/http2.py", line 273, in _receive_stream_event
    self._receive_events(request, stream_id)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_sync/http2.py", line 294, in _receive_events
    events = self._read_incoming_data(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_sync/http2.py", line 378, in _read_incoming_data
    raise exc
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_sync/http2.py", line 364, in _read_incoming_data
    data = self._network_stream.read(self.READ_NUM_BYTES, timeout)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 26, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/bot/animeworldo.py", line 10, in <module>
    import animeworld
  File "/home/ubuntu/.local/lib/python3.10/site-packages/animeworld/__init__.py", line 4, in <module>
    from .utility import find
  File "/home/ubuntu/.local/lib/python3.10/site-packages/animeworld/utility.py", line 163, in <module>
    SES = MySession() # sessione contenente Cookie e headers
  File "/home/ubuntu/.local/lib/python3.10/site-packages/animeworld/utility.py", line 23, in __init__
    self.fixCookie()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/animeworld/utility.py", line 31, in fixCookie
    res = self.get("https://www.animeworld.so", follow_redirects=False)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 1041, in get
    return self.request(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out
```
animeworld api versione 1.6.0, anche aggiornando alla 1.6.1 l'errore rimane

**Comment by redooo98** [comment]
ho visto ora che https://www.animeworld.so/ è offline, penso sia proprio quello il problema?

**Comment by MainKronos** [comment]
Vedi ancora il sito di https://www.animeworld.so/ offline? 
Ieri sera stavo proprio lavorando alla libreria, e facendo i consueti test ho trovato tutto normale e il sito raggiungibile...
